In [10]:
import pandas as pd
import importlib
import sys

sys.path.append("../src")

import feature_engineering

importlib.reload(feature_engineering)

from feature_engineering import FeatureEngineering

In [11]:
df = pd.read_csv("../datasets/raw/Banglore_traffic_Dataset.csv")

df.head()

,Date,Area Name,Road/Intersection Name,Traffic Volume,Average Speed,Travel Time Index,Congestion Level,Road Capacity Utilization,Incident Reports,Environmental Impact,Public Transport Usage,Traffic Signal Compliance,Parking Usage,Pedestrian and Cyclist Count,Weather Conditions,Roadwork and Construction Activity
0,2022-01-01,Indiranagar,100 Feet Road,50590,50.230299,1.500000,100.000000,100.000000,0,151.180,70.632330,84.044600,85.403629,111,Clear,No
1,2022-01-01,Indiranagar,CMH Road,30825,29.377125,1.500000,100.000000,100.000000,1,111.650,41.924899,91.407038,59.983689,100,Clear,No
2,2022-01-01,Whitefield,Marathahalli Bridge,7399,54.474398,1.039069,28.347994,36.396525,0,64.798,44.662384,61.375541,95.466020,189,Clear,No
3,2022-01-01,Koramangala,Sony World Junction,60874,43.817610,1.500000,100.000000,100.000000,1,171.748,32.773123,75.547092,63.567452,111,Clear,No
4,2022-01-01,Koramangala,Sarjapur Road,57292,41.116763,1.500000,100.000000,100.000000,3,164.584,35.092601,64.634762,93.155171,104,Clear,No

In [12]:
fe = FeatureEngineering(df)

df = fe.convert_date()

df = fe.extract_date_features()

df = fe.encode_weather()

df = fe.encode_roadwork()

df = fe.traffic_category()

df.head()

,Date,Area Name,Road/Intersection Name,Traffic Volume,Average Speed,Travel Time Index,Congestion Level,Road Capacity Utilization,Incident Reports,Environmental Impact,...,Pedestrian and Cyclist Count,Weather Conditions,Roadwork and Construction Activity,Year,Month,Day,DayOfWeek,Weather,Roadwork,Traffic Category
0,2022-01-01,Indiranagar,100 Feet Road,50590,50.230299,1.500000,100.000000,100.000000,0,151.180,...,111,Clear,No,2022,1,1,5,0,0,Severe
1,2022-01-01,Indiranagar,CMH Road,30825,29.377125,1.500000,100.000000,100.000000,1,111.650,...,100,Clear,No,2022,1,1,5,0,0,Heavy
2,2022-01-01,Whitefield,Marathahalli Bridge,7399,54.474398,1.039069,28.347994,36.396525,0,64.798,...,189,Clear,No,2022,1,1,5,0,0,Low
3,2022-01-01,Koramangala,Sony World Junction,60874,43.817610,1.500000,100.000000,100.000000,1,171.748,...,111,Clear,No,2022,1,1,5,0,0,Severe
4,2022-01-01,Koramangala,Sarjapur Road,57292,41.116763,1.500000,100.000000,100.000000,3,164.584,...,104,Clear,No,2022,1,1,5,0,0,Severe

In [13]:
df.columns

Index(['Date', 'Area Name', 'Road/Intersection Name', 'Traffic Volume',
       'Average Speed', 'Travel Time Index', 'Congestion Level',
       'Road Capacity Utilization', 'Incident Reports', 'Environmental Impact',
       'Public Transport Usage', 'Traffic Signal Compliance', 'Parking Usage',
       'Pedestrian and Cyclist Count', 'Weather Conditions',
       'Roadwork and Construction Activity', 'Year', 'Month', 'Day',
       'DayOfWeek', 'Weather', 'Roadwork', 'Traffic Category'],
      dtype='str')

In [14]:
import os

os.makedirs("../datasets/processed", exist_ok=True)

df.to_csv(
    "../datasets/processed/traffic_processed.csv",
    index=False
)

print("Processed dataset saved successfully.")

Processed dataset saved successfully.